# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "2"

services:
  nginx-proxy:
    container_name: nginx
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs"
    restart: always

  letsencrypt-nginx-proxy-companion:
    container_name: letsencrypt
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    restart: always
  
  mmt-server:
    build:
      context: .
      dockerfile: Dockerfile.mmt
    container_name: mmt-server
    restart: always
    entrypoint: ["java", "-jar", "/root/MMT/deploy/mmt.jar", "-w", "--mbt=/startup.mbt"]
    environment:
      VIRTUAL_HOST: mmt.mosis.mathhub.info
      LETSENCRYPT_HOST: mmt.mosis.mathhub.info
      LETSENCRYPT_EMAIL: admin@mathhub.info
      VIRTUAL_PORT: 80
    ports:
      - "9000:9000"
    volumes:
      - "mmtdata:/content"

  hub-db:
    image: postgres:9.5
    container_name: jupyterhub-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${DB_VOLUME_CONTAINER}
    env_file:
      - secrets/postgres.env
    volumes:
      - "db:${DB_VOLUME_CONTAINER}"

  hub:
    depends_on:
      - hub-db
    build:
      context: .
      dockerfile: Dockerfile.jupyterhub
      args:
        JUPYTERHUB_VERSION: ${JUPYTERHUB_VERSION}
    restart: always
    image: jupyterhub
    container_name: jupyterhub
    volumes:
      # Bind Docker socket on the host so we can connect to the daemon from
      # within the container
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      # Bind Docker volume on host for JupyterHub database and cookie secrets
      - "data:${DATA_VOLUME_CONTAINER}"
    ports:
      - "80"
    links:
      - hub-db
    environment:
      VIRTUAL_HOST: mosis.mathhub.info
      LETSENCRYPT_HOST: mosis.mathhub.info
      LETSENCRYPT_EMAIL: admin@mathhub.info
      VIRTUAL_PORT: 80

      # All containers will join this network
      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}

      # JupyterHub will spawn these Notebook images for users
      # The MMT Kernel Image
      DOCKER_NOTEBOOK_IMAGE_MMT: ${LOCAL_NOTEBOOK_IMAGE_MMT}
      # The Interview Notebook Image
      DOCKER_NOTEBOOK_IMAGE_INTERVIEW: ${LOCAL_NOTEBOOK_IMAGE_INTERVIEW}

      # Notebook directory inside user image
      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      # Using this run command (optional)
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}
      # Postgres db info
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: hub-db
    env_file:
      - secrets/postgres.env
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  data:
    external:
      name: ${DATA_VOLUME_HOST}
  db:
    external:
      name: ${DB_VOLUME_HOST}
  mmtdata:
  portainer:
  vhost:
  html:
  certs:

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}